### PR TITLE
Yjs echo WS

### PR DESCRIPTION
**Pull request by jtpio**
cc @hbcarlos 

This is a rebased version of https://github.com/QuantStack/jupyterlab/pull/2, with the two commits from #2.

Let me know if works locally. Thanks!

### CODE REVIEW

**Comment by jtpio** [comment]
Otherwise this Binder link should also work:

[Binder](https://mybinder.org/v2/gh/QuantStack/jupyterlab/echo-server?urlpath=lab-dev)

(but can take a while to build)

**Comment by hbcarlos** [comment]
It's working
You can merge.

**Comment by hbcarlos** [comment]
Thanks Jeremy!! : )

**Comment by jtpio** [comment]
cc @dmonad since it's targeting the `yjupyter` branch.

**Comment by dmonad** [comment]
Neat, thanks :)

**Pull request merged**
